spring:
  datasource:
    url: jdbc:mysql://mysql:3306/copdmanagedb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: copdmanagedb

cors:
  front-app-url: http://app:80